defaults: &defaults
  docker:
    - image: circleci/golang:1.13
  working_directory: /go/src/github.com/djthorpe/googlecast

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: make test
  build:
    <<: *defaults
    steps:
      - checkout
      - run: make build

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build

